[tool.poetry]
name = "battery"
version = "0.1.0"
description = ""
authors = ["Felipe Castro"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
psutil = "^6.1.0"
plyer = "^2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
